services:
  apache:
    build: .
    ports:
      - 8868:80
    links:
      - mysql
    volumes:
      - ./source/:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - 8869:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app123

